name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.1.9
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
